---
abstract: ~
author:
  - 'Matt S. Trout, <mst@shadowcatsystems.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-ResultSource-MultipleTableInheritance
no_index:
  directory:
    - inc
    - t
requires:
  Carp::Clan: 0
  DBIx::Class: 0
  Method::Signatures::Simple: 0
  String::TT: 0
  aliased: 0
  namespace::autoclean: 0
  parent: 0
  signatures: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
